export interface MRDInfo {
    "id": string,
    "mrdNumber": string,
    "countryOfOrigin": string,
    "countryOfSupply": string,
    "modeOfShipping": string,
    "destination": string,
    "soldTo": string,
    "shipTo": string,
    "userId": string,
    "createdDate": string,
    "totalUnitPrice": string,
    "sumTotal": string,
    "comment": string,
    "claim": string,
    "freightForwarderId": string,
    "freightForwarder": any,
    "commercialInvoice": any,
    "commercialInvoices": any,
    "packingList": any,
    "packingLists": any,
    "supplierSLADays": string,
    "freightForwarderSLADays": string,
    "materialReadinessDocumentStatus": string,
    "purchaseOrderId": string,
    "pickedUp": boolean,
    "supplierId": string,
    "length": string,
    "weight": string,
    "height": string,
    "grossWeight": string,
    "purchaseOrderNumber": string,
    "proofOfCollection": any,
    "pickUpAddress":string
}

export interface SelectedMRD {
    "id": string,
    "mrdNumber": string,
    "createdDate": string,
    "countryOfSupply": string,
    "pickUpAddress": string,
    "destination": string,
    "totalBatchedPOs": number
}